app/urls.py
from django.urls import path,include

from . import views

urlpatterns = [
	path('', views.store, name="store"),
	path('', include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),

	path('category/', views.categories, name="category"),
	path('cart/', views.cart, name="cart"),
	path('checkout/', views.checkout, name="checkout"),

	path('update_item/', views.updateItem, name="update_item"),
	path('process_order/', views.processOrder, name="process_order"),
	path("search/", views.search, name="search"),

	path('more/<str:pk>/', views.viewMore, name="more"),
	path('profile/<str:pk>/', views.profile, name="profile"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    first_name = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True)
   
	
	 # USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['first_name','last_name']


class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	joined_on = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.first_name + ' ' + self.user.last_name

class Category(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Product(models.Model):
	name = models.CharField(max_length=200)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	price = models.FloatField()
	digital = models.BooleanField(default=False,null=True, blank=True)
	image = models.ImageField(null=True, blank=True)

	def __str__(self):
		return self.name

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)
	STATUS = (('Order Received','Order Received'),('Ready for  Pickup','Ready for  Pickup'))
	status = models.CharField(max_length=50, choices=STATUS, null=True,default='Order Received')

	def __str__(self):
		return "#Order: " + str(self.id)
	
	# Sending sms when payment is completed

	# def save(self, *args, **kwargs):
	# 	if self.complete == True:
	# 		account_sid = 'AC1c51c3361f816c86025c5959fb4c1639' 
	# 		auth_token = '0afd00b31e3bce1679ac101b742bbaeb' 
	# 		client = Client(account_sid, auth_token) 
			
	# 		message = client.messages.create(  
	# 									messaging_service_sid='MGe1b04e835f62fe804cd97889a04cd596', 
	# 									body='Hello Gilbert, thankyou for shopping with us, you will be notified once the Product is ready for pickup',      
	# 									to='+254725060098' 
	# 								) 
			
	# 		print(message.sid)

	# 		return super().save(*args, **kwargs)

		
	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total 

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.product.price * self.quantity
		return total
	

	def __str__(self):
		return self.product
		

class ShippingAddress(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address

app/templates/cart.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Cart{% endblock %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-success" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> Ksh.{{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>

							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Ksh.{{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrowa-down.png' %}">

							
						</div>
					</div>
					<div style="flex:1"><p>Ksh.{{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

app/templates/category.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}

<form class="header__search" method="GET" action="{% url 'search' %}">
  <label>
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>search</title>
          <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
          </path>
      </svg>
      <input name="q" placeholder="Search for product" />
  </label>
</form>

<div>
    {% for category in categories %}
    <h4>{{category.title}}</h4><hr>

    <div class="row category-products">

        {% for product in category.product_set.all %}
        <div class="col-lg-4">
          <a href="{% url 'more' product.id %}">
        
            <img class="thumbnail" src="{{product.imageURL}}" />
          
          </a>
          <div class="box-element product">
            <h6><strong>{{product.name}}</strong></h6>
            <hr />
      
            <button
              data-product="{{product.id}}"
              data-action="add"
              class="btn btn-success add-btn update-cart">
              Add to Cart
            </button>
      
            <a class="btn btn-outline-dark" href="{% url 'more' product.id %}">View</a>
            <h5 style="display: inline-block; float: right">
              <strong>Ksh.{{product.price}}</strong>
            </h5>
          </div>
        </div>
        {% endfor %}
      
      </div>
      {% endfor %}
</div>




{% endblock content %}

app/templates/checkout.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Checkout{% endblock %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<!--<button id="make-payment">Make payment</button>-->
				<div id="paypal-button-container"></div>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-success" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>Ksh.{{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   Ksh.{{order.get_cart_total|floatformat:2}}</h5>
			</div>
		</div>
	</div>

	<script src="https://www.paypal.com/sdk/js?client-id=AW5_t6yeYUC9PyTFQtMR4bLM0SMbryEvVuKx-4P59hf1Y8LfFJyCg66HQFqXrIRMjyxAt31prbgQuGiI&currency=USD&disable-funding=credit"></script>

	<script>
		var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

        	style: {
                color:  'blue',
                shape:  'rect',
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value:parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    submitFormData()
                });
            }

        }).render('#paypal-button-container');
    </script>

	<script type="text/javascript">
		var shipping = '{{order.shipping}}'

		if (shipping == 'False'){
		 	document.getElementById('shipping-info').innerHTML = ''
		}

		if (user != 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping == 'False' && user != 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
				document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
			    document.getElementById('payment-info').classList.remove("hidden");
		}

		var form = document.getElementById('form')
		form.addEventListener('submit', function(e){
	    	e.preventDefault()
	    	console.log('Form Submitted...')
	    	document.getElementById('form-button').classList.add("hidden");
	    	document.getElementById('payment-info').classList.remove("hidden");
	    })

		/*
	    document.getElementById('make-payment').addEventListener('click', function(e){
	    	submitFormData()
	    })
	    */

	    function submitFormData(){
	    	console.log('Payment button clicked')

	    	var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping != 'False'){
	    		shippingInfo.address = form.address.value
		    	shippingInfo.city = form.city.value
		    	shippingInfo.state = form.state.value
		    	shippingInfo.zipcode = form.zipcode.value
	    	}

	    	if (user == 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}

	    	console.log('Shipping Info:', shippingInfo)
	    	console.log('User Info:', userFormData)

	    	var url = "/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		}, 
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),
	    		
	    	})
	    	.then((response) => response.json())
	    	.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');  

				cart = {}
				document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"

				window.location.href = "{% url 'store' %}"

				})
	    }
	</script>
{% endblock content %}


 

app/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{% block title %}{% endblock %}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<!-- <link
	rel="stylesheet"
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
	integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
	crossorigin="anonymous" /> -->

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            // Does this cookie string begin with the name we want?
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getToken('csrftoken')

		function getCookie(name) {
		    // Split cookie string and get all individual name=value pairs in an array
		    var cookieArr = document.cookie.split(";");

		    // Loop through the array elements
		    for(var i = 0; i < cookieArr.length; i++) {
		        var cookiePair = cookieArr[i].split("=");

		        /* Removing whitespace at the beginning of the cookie name
		        and compare it with the given string */
		        if(name == cookiePair[0].trim()) {
		            // Decode the cookie value and return
		            return decodeURIComponent(cookiePair[1]);
		        }
		    }

		    // Return null if not found
		    return null;
		}
		var cart = JSON.parse(getCookie('cart'))

		if (cart == undefined){
			cart = {}
			console.log('Cart Created!', cart)
			document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)
	
	</script>

</head>
<body>

	{% include 'navbar.html' %}
     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


	 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 

	<!-- <script
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
	integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
	crossorigin="anonymous">
  </script> -->

	<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

app/templates/more.html
{% extends 'main.html' %}
{% load static %}
{% block title %}View More{% endblock %}
{% block content %}
<div class="view-more">

  <div class="row more">
    <div class="col-2"></div>
    
    <div class="col-8 card product-details">

      <img class="thumbnail-more" src="{{product.imageURL}}" />
      <div class="box-element product">
        <h4><strong>{{product.name}}</strong></h4>
        <hr />
        <span>★★★★★</span>
        <h5>Product Model</h5>
        <h6 style="color:maroon">Few units left</h6>

        <h5>
          <strong>Ksh.{{product.price}}</strong>
        </h5>

        <hr />
  
        <button
          data-product="{{product.id}}"
          data-action="add"
          class="btn btn-success add-btn update-cart btn-block">
          Add to Cart
        </button>

       
      </div>

      <div>

        <h3>Product details</h3>
  
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
          Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
          when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
          It has survived not only five centuries, but also the leap into electronic typesetting,
           remaining essentially unchanged. It was popularised in the 1960s with the release 
           of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop 
           publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
        
      </div>
     
   

    </div>
    <div class="col-2"></div>
   
  </div>

  {% endblock content %}

app/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'store' %}">Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'store' %}">Store <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'category' %}">Categories <span class="sr-only"></span></a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cart' %}">Cart <span class="sr-only"></span></a>
        </li>
   
      </ul>
      <div class="form-inline my-2 my-lg-0">
       
            <div class="nav-item dropdown">
                <a style="color:white" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'profile' user.id %}">Profile</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                {% endif %}
                
                </div>
                
            </div>

            {% if page_name == 'store' or page_name == 'categories' or page_name == 'cart' or page_name == 'viewMore' or page_name == 'checkout' or page_name == 'search' %}

           <a href="{% url 'cart' %}">
              <img  id="cart-icon" src="{% static 'images/cart.jpg' %}">
          </a>
          <p id="cart-total">{{cartItems}}</p>

          {%  endif %}

      </div>
    </div>
  </nav>

app/templates/profile.html
{% extends 'main.html' %}
{% load static %}
{% block title %}My Profile{% endblock %}
{% block content %}
<div class="profile-page">
    <div class="row">
        <div class="col-md-4">
            <h3 class="profile-header">Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span>{{name}}</p>
            <p><span class="font-weight-bold">Username: </span>{{customer.user}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Joined on: </span>{{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3 class="profile-header">Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in customer.order_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>#Order {{order.id}}</td>
                        <td>{{order.date_ordered|timesince}} ago</td>
                        {% if order.complete == False %}
                        <td style="color: red;">Notyet Paid</td>

                        {% elif order.status == 'Order Received' %}
                        <td style="color: blue;">Order Received</td>

                        {% else %}
                        <td style="color: green;">{{order.status}}</td>

                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

app/templates/search.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Search{% endblock %}
{% block content %}

<form class="header__search" method="GET" action="{% url 'search' %}">
    <label>
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
            </path>
        </svg>
        <input name="q" placeholder="Search for product" />
    </label>
  </form>
   <hr>  

<div class="row">

  {% if results %}

    {% for result in results %}

    <div class="col-lg-4">
      <a href="{% url 'more' result.id %}">
        
        <img class="thumbnail" src="{{result.imageURL}}" />
      
      </a>
        
        <div class="box-element product">
          <h6><strong>{{result.name}}</strong></h6>
          <hr />
    
          <button
            data-product="{{result.id}}"
            data-action="add"
            class="btn btn-success add-btn update-cart">
            Add to Cart
          </button>
    
          <a class="btn btn-outline-dark" href="{% url 'more' result.id %}">View</a>
          <h5 style="display: inline-block; float: right">
            <strong>Ksh.{{result.price}}</strong>
          </h5>
        </div>
      </div>


    {% endfor %}

    {% else %}
    <h3 style="color: maroon;">No Match Found!!</h3>

    {% endif %}

</div>
{% endblock content %}

app/templates/store.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Store{% endblock %}
{% block content %}

<form class="header__search" method="GET" action="{% url 'search' %}">
  <label>
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>search</title>
          <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
          </path>
      </svg>
      <input name="q" placeholder="Search for product" />
  </label>
</form>


<h4>All Products</h4>
<div class="row">

  {% for product in products %}
  <div class="col-lg-4">
    <a href="{% url 'more' product.id %}">
        
      <img class="thumbnail" src="{{product.imageURL}}" />
    
    </a>
    <div class="box-element product">
      <h6><strong>{{product.name}}</strong></h6>
      <hr />

      <button
        data-product="{{product.id}}"
        data-action="add"
        class="btn btn-success add-btn update-cart">
        Add to Cart
      </button>

      <a class="btn btn-outline-dark" href="{% url 'more' product.id %}">View</a>
      <h5 style="display: inline-block; float: right">
        <strong>Ksh.{{product.price}}</strong>
      </h5>
    </div>
  </div>
  {% endfor %}

</div>

    <ul class="pagination">
      {% if products.has_previous %}

      <li class="page-item">
        <a href="?page={{ products.previous_page_number }}" class="page-link">&laquo;</a>
      </li>

      {% endif %}
      {%  for p in products.paginator.page_range %}

      {% if products.number == p %}
      
      <li class="page-item active">
        <a href="?page={{p}}" class="page-link">{{p}}</a>
      </li>

      {% else %}

      <li class="page-item">
        <a href="?page={{p}}" class="page-link">{{p}}</a>
      </li>

      {% endif %}

      {% endfor %}


      {% if products.has_next %}

      <li class="page-item">
        <a href="?page={{ products.next_page_number }}" class="page-link">&raquo;</a>
      </li>

      {% endif %}

    </ul>


{% endblock content %}